server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
    #register-with-eureka: false
  
  instance:
    instance-id: enjoyCloud-zuul-gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）

spring:
  application:
    name: enjoyCloud-zuul-gateway
  
  security:
    user:
      name: admin
      password: enjoy  
zuul:
 routes:
   # 方式一
   # enjoyCloud-provider-user: /user-proxy/**
   
   #方式二
   user.path: /user-proxy/**
   user.serviceId: enjoyCloud-provider-user
   
   
   product:
      path: /product-proxy/**
      serviceId: enjoyCloud-provider-product
 ignored-services: #忽略掉用户服务的名称
    #enjoyCloud-provider-user
    "*"
 #设置公共前缀   
 prefix: /enjoy-api